module Environment
  class Public
    def build
      ENV["SIGH_APP_IDENTIFIER"] = ENV["APP_IDENTIFIER"]
      ENV["SIGH_USERNAME"] = ENV["FASTLANE_USER"]
      ENV["SIGN_READONLY"] = ENV["GIT_READONLY"]
      
      ENV["MATCH_APP_IDENTIFIER"] = ENV["APP_IDENTIFIER"]
      ENV["MATCH_READONLY"] = ENV["GIT_READONLY"]
      ENV["MATCH_GIT_URL"] = ENV["GIT_CERT_REPO"]
      ENV["MATCH_GIT_BRANCH"] = ENV["GIT_BRANCH"]
      ENV["MATCH_PASSWORD"] = ENV["GIT_SECRET"]
      ENV["MATCH_USERNAME"] = ENV["FASTLANE_USER"]
      ENV["MATCH_CLONE_BRANCH_DIRECTLY"] = "true"
      ENV["MATCH_TYPE"] = "appstore"
  
      ENV["FL_UPDATE_APP_IDENTIFIER_PROJECT_PATH"] = ENV["PROJECT_DIR"]
      ENV["FL_UPDATE_APP_IDENTIFIER_PLIST_PATH"] = ENV["PLIST_DIR"]
      ENV["FL_UPDATE_APP_IDENTIFIER"] = ENV["APP_IDENTIFIER"]
  
      ENV["FL_PROJECT_PROVISIONING_PROJECT_PATH"] = ENV["PROJECT_DIR"]
      ENV["FL_PROJECT_PROVISIONING_PROFILE_FILE"] = "./AppStore_#{ENV["APP_IDENTIFIER"]}.mobileprovision"
  
      ENV["GYM_SCHEME"] = ENV["SCHEME"]
      ENV["GYM_WORKSPACE"] = ENV["PROJECT_WORKSPACE"]
      ENV["GYM_INCLUDE_BITCODE"] = "true"
  
      ENV["PILOT_TEAM_ID"] = ENV["TEAM_ID"]
      ENV["PILOT_APPLE_ID"] = ENV["FASTLANE_USER"]
      ENV["PILOT_USERNAME"] = ENV["FASTLANE_USER"]
      ENV["PILOT_APP_IDENTIFIER"] = ENV["APP_IDENTIFIER"]
      ENV["PILOT_DISTRIBUTE_EXTERNAL"] = "false"
      ENV["PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING"] = "true"

      ENV["SUPPLY_JSON_KEY"] = ENV["JSON_KEY"]
      ENV["SUPPLY_PACKAGE_NAME"] = ENV["ANDROID_PACKAGE_NAME"]
      ENV["SUPPLY_SKIP_UPLOAD_IMAGES"] = "true"
      ENV["SUPPLY_SKIP_UPLOAD_SCREENSHOTS"] = "true"
    end
  end
end