export const USER_PREFERRED_CURRENCY = '@TronWallet:userPreferredCurrency'
export const USER_PREFERRED_LANGUAGE = '@TronWallet:userPreferredLanguage'
export const USER_STATUS = '@TronWallet:useStatus'
export const ALWAYS_ASK_PIN = '@TronWallet:alwaysAskPin'
export const USER_FILTERED_TOKENS = '@TronWallet:userFilteredTokens'
export const ADD = 'ADD'
export const EDIT = 'EDIT'
export const FIXED_TOKENS = ['TRX', 'TWX', 'LoveHearts']
export const FEATURED_TOKENS = ['TWX', 'LoveHearts']
